version: '3.9'
services:
  ms-youtube-mixer:
    env_file:
      - ./back/ms-youtube-mixer/.env
    container_name: ms-youtube-mixer
    build:
      context: ./back/ms-youtube-mixer
      dockerfile: Dockerfile
    ports:
      - ${MS_YT_MIXER_PORT}:${MS_YT_MIXER_PORT}
    volumes:
      - .:/usr/src/app

  ms-transcribe:
    env_file:
      - ./back/ms-transcribe/.env
    container_name: ms-transcribe
    build:
      context: ./back/ms-transcribe
      dockerfile: Dockerfile
    ports:
      - ${MS_TRANSCRIBE_PORT}:${MS_TRANSCRIBE_PORT}
    volumes:
      - .:/usr/src/app
