version: '3.9'
services:
  ms-youtube-mixer:
    env_file:
      - ./back/ms-youtube-mixer/.env
    container_name: ms-youtube-mixer
    build:
      context: ./back/ms-youtube-mixer
      dockerfile: Dockerfile
    ports:
      - ${MS_YT_MIXER_PORT}:${MS_YT_MIXER_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/back/ms-youtube-mixer/files
      - /usr/src/app/back/ms-youtube-mixer/tmp

  ms-transcribe:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    env_file:
      - ./back/ms-transcribe/.env
    container_name: ms-transcribe
    build:
      context: ./back/ms-transcribe
      dockerfile: Dockerfile
    ports:
      - ${MS_TRANSCRIBE_PORT}:${MS_TRANSCRIBE_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/back/ms-transcribe/files
      - /usr/src/app/back/ms-transcribe/zip_files
